<a href="https://colab.research.google.com/github/philthefeel/Practica_amb_programacio_numerica/blob/main/S03_T04_Pr%C3%A0ctica_amb_programaci%C3%B3_num%C3%A8rica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercici 1
- Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.




In [1]:
import numpy as np
from scipy import stats as stat

In [10]:
def descrip_stats(npArray):
    '''
    Performing multiple Descriptive statistics from a matrix of 1 dim
    '''
    if npArray.ndim == 1:
      print("Size = {} \n".format(npArray.size),
            "[Min, Max] = [{} {}]\n".format(np.min(npArray), np.max(npArray)),
            "IQR = {}\n".format(stat.iqr(npArray)),
            "Median = {}\n".format(np.median(npArray)),
            "Mean = {}\n".format(np.mean(npArray)),
            "SD = {}\n".format(round(np.std(npArray)),2),
            "Varianza = {}\n".format(np.var(npArray))
      )
    else:
      print("ERROR: ARRAY SHOULD HAVE 1 DIMENSION, INSTEAD OF {} DIMENSION".format(npArray.ndim))



In [4]:
npArray_test1 = np.array(range(1,5))
print(npArray_test1)
descrip_stats(npArray_test1)

[1 2 3 4]
Size = 4 
 [Min, Max] = [1 4]
 IQR = 1.5
 Median = 2.5
 Mean = 2.5
 SD = 1
 Varianza = 1.25



In [11]:
npArray_test2 = np.array([range(1,4), range(1,4)])
print(npArray_test2)
descrip_stats(npArray_test2)

[[1 2 3]
 [1 2 3]]
ERROR: ARRAY SHOULD HAVE 1 DIMENSION, INSTEAD OF 2 DIMENSION


In [13]:
npArray_test0 = np.array(3)
print(npArray_test0)
descrip_stats(npArray_test0)

3
ERROR: ARRAY SHOULD HAVE 1 DIMENSION, INSTEAD OF 0 DIMENSION


# Exercici 2
- Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [14]:
def mtx_from_n(num):
    '''
    Retrieving a N x N array from a number of dimension
    '''
    return np.random.randint(low=0,
                             high=100,
                             size=(num, num),
                             dtype=int)

In [18]:
mtx_test1 = mtx_from_n(5)
print(mtx_test1)
mtx_test1.shape

[[85 10 19  1 60]
 [61 26 56 44 32]
 [52 45 26 94 45]
 [76 31 81 70 13]
 [24 73  7  8 56]]


(5, 5)

# Exercici 3
- Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [21]:
def colRowSum(mat2D):
    '''
    Retrieving from 2D: ColSum and RowSum
    '''
    c = np.sum(mat2D, axis=0)
    r = np.sum(mat2D, axis=1)
    print("ColSum = {}\nRowSum = {}\n".format(c,r))



In [22]:
mtx_2D = np.array([[1,0,3], [3,0,1]])
print(mtx_2D)
colRowSum(mtx_2D)

[[1 0 3]
 [3 0 1]]
ColSum = [4 0 4]
RowSum = [4 4]



# Exercici 4
- Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [41]:
# Creating variables to test
var_1 = np.array([2,3,14,28])
var_2 = np.array([30,1,5,8])
var_3 = np.array([28,14,3,2])

# Mean
def mymean(X):
  XMEAN = sum(X)/len(X)
  return XMEAN
# Variance
def myVariance(X):
  mean_dif = sum((X - mymean(X))**2)
  VARIANCE = mean_dif/len(X)
  return VARIANCE
# SD
def mySD(X):
  SD = myVariance(X)**(1/2)
  return SD

In [49]:
def corrTest(X, Y):
    '''
    Performing Correlation Coefficient 
    Values in Range -1 to 1. 
    Closer to 1 means that the correlation is strong, direct and positive
    Closer to -1 means that the correlation is strong, inverse and negative
    Closer to 0 means that there is a weak relation between variables 
    '''
    Xmean = mymean(X)
    Ymean = mymean(Y)
    # print([Xmean, Ymean])
    XSD = mySD(X)
    YSD = mySD(Y)
    # print([XSD, YSD])
    COVARXY = (sum(X*Y) / len(X)) - (Xmean * Ymean)

    RXY = COVARXY / (XSD * YSD)

    return RXY

In [47]:
# When comparing the same list (both variables increase together)
print(corrTest(var_1,var_1))
# When comparing the list With negative list, the correlation is inverse (negative)
print(corrTest(var_1,-var_1))
# When comparing two different list
print(corrTest(var_1,var_2))
# When comparing two different list
print(corrTest(var_3,var_2))

1.0000000000000002
-1.0000000000000002
-0.33880402705336293
0.7792492622227348
